/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto.individual;

/**
 *
 * @author Aluno
 */
public class ProjetoRapha extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoRapha
     */
    public ProjetoRapha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        tfCampoMensal = new javax.swing.JTextField();
        tfCampoAnual = new javax.swing.JTextField();
        tfCampoProdutosTotal = new javax.swing.JTextField();
        tfCampoProdutosPerdidos = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblProdutosTotal = new javax.swing.JLabel();
        lblProdutosPerdidos = new javax.swing.JLabel();
        btnVerficarProduto = new javax.swing.JButton();
        lblTituloPorcentagem = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblQtdProdutoPerdido = new javax.swing.JLabel();
        tfSolucao = new javax.swing.JTextField();
        lblSolucao = new javax.swing.JLabel();
        lblTituloResultadoSolucao = new javax.swing.JLabel();
        lblValorSolucao = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfCampoMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoMensalActionPerformed(evt);
            }
        });

        tfCampoProdutosTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoProdutosTotalActionPerformed(evt);
            }
        });

        tfCampoProdutosPerdidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoProdutosPerdidosActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel1.setText("Insira sua fatura mensal:");

        jLabel2.setText("Fatura Anual:");

        lblProdutosTotal.setText("Insira quantos produtos você tem:");

        lblProdutosPerdidos.setText("Insira quantos produtos você perdeu:");

        btnVerficarProduto.setText("Verificar");
        btnVerficarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerficarProdutoActionPerformed(evt);
            }
        });

        lblTituloPorcentagem.setText("Você teve um prejuízo de:");

        lblResultado.setText("0");

        jLabel3.setText("Quantidades de produtos que restou:");

        lblQtdProdutoPerdido.setText("0");

        tfSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSolucaoActionPerformed(evt);
            }
        });

        lblSolucao.setText("Quantidades de perdas:");

        lblTituloResultadoSolucao.setText("Quantos você economizará com a nossa solução:");

        lblValorSolucao.setText("0");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfCampoAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcular)
                                .addGap(4, 4, 4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(tfCampoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblTituloPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultado)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(lblQtdProdutoPerdido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(tfCampoProdutosPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(tfCampoProdutosTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lblProdutosTotal)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(236, 236, 236)
                                        .addComponent(tfSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(239, 239, 239)
                                        .addComponent(btnConfirmar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(216, 216, 216)
                                        .addComponent(lblSolucao)))
                                .addGap(0, 28, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProdutosPerdidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTituloResultadoSolucao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorSolucao)))
                .addGap(511, 511, 511))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(btnVerficarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCampoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(tfCampoAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProdutosTotal)
                            .addComponent(lblSolucao))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCampoProdutosTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProdutosPerdidos)
                                .addGap(12, 12, 12)
                                .addComponent(tfCampoProdutosPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTituloResultadoSolucao)
                                    .addComponent(lblValorSolucao))
                                .addGap(28, 28, 28)
                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblQtdProdutoPerdido))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloPorcentagem)
                            .addComponent(lblResultado))))
                .addGap(18, 18, 18)
                .addComponent(btnVerficarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCampoMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoMensalActionPerformed

    private void tfCampoProdutosTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoProdutosTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoProdutosTotalActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String texto = tfCampoMensal.getText();
        Double calculo = Double.parseDouble(texto);
//        

        
       //Fatura Mensal:
        Double mensal = calculo;
        
       //Fatura Anual:
        Double anual = (calculo * 12);
        tfCampoAnual.setText(String.format("R$%.2f", anual));
       
       
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void tfCampoProdutosPerdidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoProdutosPerdidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoProdutosPerdidosActionPerformed

    private void btnVerficarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerficarProdutoActionPerformed
       String InsiraProduto = tfCampoProdutosTotal.getText();
       Double QtdProduto = Double.valueOf(InsiraProduto);
       
      String InsiraProdutoPerdido = tfCampoProdutosPerdidos.getText();
      Integer QtdProdutoPerdido = Integer.valueOf(InsiraProdutoPerdido);
      
      String puxandoProdutoPerdido = tfCampoProdutosPerdidos.getText();
      tfSolucao.setText(puxandoProdutoPerdido);
      
      Double calcularProduto = QtdProduto - QtdProdutoPerdido; 
        
      Double economia = calcularProduto / QtdProduto;
       
      Double porcentagem = 100 - (economia * 100);
       
      lblQtdProdutoPerdido.setText(calcularProduto.toString());
       
      lblResultado.setText(String.format("%.1f%%", porcentagem));
      
    }//GEN-LAST:event_btnVerficarProdutoActionPerformed

    private void tfSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSolucaoActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        String InsiraRestoDoProduto = tfSolucao.getText();
        Double qtdRestoDeProduto = Double.valueOf(InsiraRestoDoProduto); 
       
      //Quantos economizará em relação a perda. 
      // Exemplo: se ele o cliente tem 2000 produtos e perdeu 200
      // nossa solução reduzará 90% desse 200
      //logo, ficará 180, ou seja, estamos evitando perda de 20 produtos
       Double resultado = qtdRestoDeProduto * 0.90;
        
       lblValorSolucao.setText(resultado.toString());
      
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoRapha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoRapha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoRapha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoRapha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoRapha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVerficarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblProdutosPerdidos;
    private javax.swing.JLabel lblProdutosTotal;
    private javax.swing.JLabel lblQtdProdutoPerdido;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSolucao;
    private javax.swing.JLabel lblTituloPorcentagem;
    private javax.swing.JLabel lblTituloResultadoSolucao;
    private javax.swing.JLabel lblValorSolucao;
    private javax.swing.JTextField tfCampoAnual;
    private javax.swing.JTextField tfCampoMensal;
    private javax.swing.JTextField tfCampoProdutosPerdidos;
    private javax.swing.JTextField tfCampoProdutosTotal;
    private javax.swing.JTextField tfSolucao;
    // End of variables declaration//GEN-END:variables
}
